import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { format, addMonths } from 'date-fns';
import { supabase } from '../../../lib/supabase';
import { Button, Input, Label } from '../../../components/ui/basic';
import { formatCurrency } from '../../../lib/utils';
import { useAuth } from '../../../lib/AuthContext';

// ---------------------------------------------------------------------------
// EMI Loans — list view + create-new-loan modal.
//
// Interest method: FLAT (consistent with member loans).
//   total_interest = financed × (rate/100) × (tenure/12)
//   emi            = (financed + total_interest) / tenure
//
// Loan code is auto-generated by DB trigger as EUS/EMI/L/MMYYYY/NNN.
// Vendor is paid the full financed amount upfront (recorded on the loan row).
// Loan detail / payment recording lives on a separate profile page.
// ---------------------------------------------------------------------------

type Customer = { id: string; customer_code: string; full_name: string };
type Vendor   = { id: string; name: string };

type EmiLoan = {
  id: string;
  loan_code: string;
  customer_id: string;
  vendor_id: string;
  product_name: string;
  product_category: string | null;
  product_price: number;
  downpayment: number;
  financed_amount: number;
  interest_rate: number;
  tenure_months: number;
  emi_amount: number;
  total_payable: number;
  total_interest: number;
  vendor_paid_amount: number;
  vendor_paid_date: string;
  vendor_invoice_number: string | null;
  disbursed_date: string;
  first_emi_date: string;
  remaining_principal: number;
  status: 'active' | 'closed' | 'defaulted' | 'foreclosed';
  notes: string | null;
  created_at: string;
  emi_customers: { customer_code: string; full_name: string } | null;
  vendors: { name: string } | null;
};

type StatusFilter = 'all' | 'active' | 'closed' | 'defaulted' | 'foreclosed';

const DEFAULT_RATE = 18; // % per annum flat, sensible default; admin can override
const TENURE_OPTIONS = [3, 6, 9, 12, 18, 24, 36];

export function EmiLoans() {
  const navigate = useNavigate();
  const { user } = useAuth();

  const [loans, setLoans] = useState<EmiLoan[]>([]);
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [vendors, setVendors] = useState<Vendor[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  // Filters
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState<StatusFilter>('all');

  // Create modal
  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const [formLoading, setFormLoading] = useState(false);
  const [formError, setFormError] = useState('');
  const [successMessage, setSuccessMessage] = useState('');

  // Form state
  const [customerId, setCustomerId] = useState('');
  const [vendorId, setVendorId] = useState('');
  const [productName, setProductName] = useState('');
  const [productCategory, setProductCategory] = useState('');
  const [productPrice, setProductPrice] = useState('');
  const [downpayment, setDownpayment] = useState('0');
  const [interestRate, setInterestRate] = useState(String(DEFAULT_RATE));
  const [tenureMonths, setTenureMonths] = useState('12');
  const [disbursedDate, setDisbursedDate] = useState(format(new Date(), 'yyyy-MM-dd'));
  const [firstEmiDate, setFirstEmiDate] = useState(format(addMonths(new Date(), 1), 'yyyy-MM-dd'));
  const [vendorInvoiceNumber, setVendorInvoiceNumber] = useState('');
  const [notes, setNotes] = useState('');

  useEffect(() => { fetchData(); }, []);

  const fetchData = async () => {
    setLoading(true);
    try {
      const [loanRes, custRes, venRes] = await Promise.all([
        supabase
          .from('emi_loans')
          .select('*, emi_customers(customer_code, full_name), vendors(name)')
          .order('created_at', { ascending: false }),
        supabase
          .from('emi_customers')
          .select('id, customer_code, full_name')
          .order('full_name', { ascending: true }),
        supabase
          .from('vendors')
          .select('id, name')
          .order('name', { ascending: true }),
      ]);

      if (loanRes.error) throw loanRes.error;
      if (custRes.error) throw custRes.error;
      if (venRes.error)  throw venRes.error;

      setLoans(loanRes.data || []);
      setCustomers(custRes.data || []);
      setVendors(venRes.data || []);
    } catch (err: any) {
      setError(err.message || 'Failed to load EMI data');
    } finally {
      setLoading(false);
    }
  };

  // ---------- Live EMI calculation -------------------------------------------
  const calc = (() => {
    const price = Number(productPrice) || 0;
    const dp = Number(downpayment) || 0;
    const rate = Number(interestRate) || 0;
    const tenure = Number(tenureMonths) || 0;
    if (price <= 0 || tenure <= 0) {
      return { financed: 0, totalInterest: 0, totalPayable: 0, emi: 0, principalPerEmi: 0, interestPerEmi: 0 };
    }
    const financed = Math.max(0, price - dp);
    const totalInterest = (financed * rate * tenure) / (12 * 100);
    const totalPayable = financed + totalInterest;
    const emi = tenure > 0 ? totalPayable / tenure : 0;
    return {
      financed,
      totalInterest: round2(totalInterest),
      totalPayable: round2(totalPayable),
      emi: round2(emi),
      principalPerEmi: round2(financed / tenure),
      interestPerEmi: round2(totalInterest / tenure),
    };
  })();

  const resetForm = () => {
    setCustomerId(''); setVendorId('');
    setProductName(''); setProductCategory('');
    setProductPrice(''); setDownpayment('0');
    setInterestRate(String(DEFAULT_RATE));
    setTenureMonths('12');
    setDisbursedDate(format(new Date(), 'yyyy-MM-dd'));
    setFirstEmiDate(format(addMonths(new Date(), 1), 'yyyy-MM-dd'));
    setVendorInvoiceNumber('');
    setNotes('');
    setFormError('');
  };

  const openCreate = () => {
    resetForm();
    setIsCreateOpen(true);
  };

  const handleCreate = async (e: React.FormEvent) => {
    e.preventDefault();
    setFormLoading(true);
    setFormError('');
    try {
      if (!customerId)   throw new Error('Please select a customer');
      if (!vendorId)     throw new Error('Please select a vendor');
      if (!productName.trim()) throw new Error('Product name is required');
      if (Number(productPrice) <= 0) throw new Error('Product price must be greater than 0');
      if (Number(downpayment) > Number(productPrice)) throw new Error('Downpayment cannot exceed product price');
      if (calc.financed <= 0) throw new Error('Financed amount must be greater than 0 (reduce downpayment)');
      if (Number(tenureMonths) <= 0) throw new Error('Tenure must be at least 1 month');

      const payload: Record<string, unknown> = {
        customer_id: customerId,
        vendor_id: vendorId,
        product_name: productName.trim(),
        product_category: productCategory.trim() || null,
        product_price: Number(productPrice),
        downpayment: Number(downpayment) || 0,
        financed_amount: calc.financed,
        interest_rate: Number(interestRate),
        tenure_months: Number(tenureMonths),
        emi_amount: calc.emi,
        total_payable: calc.totalPayable,
        total_interest: calc.totalInterest,
        vendor_paid_amount: calc.financed, // we pay vendor the financed amount upfront
        vendor_paid_date: disbursedDate,
        vendor_invoice_number: vendorInvoiceNumber.trim() || null,
        disbursed_date: disbursedDate,
        first_emi_date: firstEmiDate,
        remaining_principal: calc.financed,
        status: 'active',
        notes: notes.trim() || null,
      };
      if (user?.id && user.id.length > 20) payload.created_by = user.id;

      const { error: insErr } = await supabase.from('emi_loans').insert(payload);
      if (insErr) throw insErr;

      setIsCreateOpen(false);
      setSuccessMessage(`EMI loan created. Vendor paid ${formatCurrency(calc.financed)}, EMI ${formatCurrency(calc.emi)} × ${tenureMonths} months.`);
      fetchData();
    } catch (err: any) {
      setFormError(err.message || 'Failed to create EMI loan');
    } finally {
      setFormLoading(false);
    }
  };

  const filtered = loans.filter(l => {
    const q = searchQuery.toLowerCase();
    const matchesSearch =
      l.loan_code.toLowerCase().includes(q) ||
      l.product_name.toLowerCase().includes(q) ||
      (l.emi_customers?.full_name || '').toLowerCase().includes(q) ||
      (l.emi_customers?.customer_code || '').toLowerCase().includes(q) ||
      (l.vendors?.name || '').toLowerCase().includes(q);
    const matchesStatus = statusFilter === 'all' || l.status === statusFilter;
    return matchesSearch && matchesStatus;
  });

  const noCustomers = customers.length === 0;
  const noVendors = vendors.length === 0;

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-3">
        <h2 className="text-xl font-bold text-gray-800">EMI Loans ({loans.length})</h2>
        <Button onClick={openCreate} className="gap-2" disabled={noCustomers || noVendors}>
          <i className="fas fa-plus"></i> New EMI Loan
        </Button>
      </div>

      {(noCustomers || noVendors) && (
        <div className="p-3 bg-yellow-50 text-yellow-800 rounded-lg text-sm border border-yellow-200">
          <i className="fas fa-info-circle mr-2"></i>
          {noCustomers && noVendors && 'Add at least one customer and one vendor before creating an EMI loan.'}
          {noCustomers && !noVendors && 'Add at least one customer (Customers tab) before creating an EMI loan.'}
          {!noCustomers && noVendors && 'Add at least one vendor (Vendors tab) before creating an EMI loan.'}
        </div>
      )}

      {successMessage && (
        <div className="p-3 bg-green-50 text-green-700 rounded-lg text-sm border border-green-200 flex justify-between">
          <span>{successMessage}</span>
          <button onClick={() => setSuccessMessage('')} className="opacity-70 hover:opacity-100">
            <i className="fas fa-times"></i>
          </button>
        </div>
      )}

      {error && (
        <div className="p-3 bg-red-50 text-red-700 rounded-lg text-sm border border-red-100">{error}</div>
      )}

      {/* Filters */}
      <div className="flex flex-col sm:flex-row gap-4 bg-white p-4 rounded-2xl shadow-sm border border-gray-100">
        <div className="flex-1 relative">
          <i className="fas fa-search absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"></i>
          <input
            type="text"
            placeholder="Search loan code, customer, vendor, product..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-10 pr-4 py-2 rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-[#1e5a48] focus:border-transparent"
          />
        </div>
        <div className="w-full sm:w-48">
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value as StatusFilter)}
            className="w-full px-4 py-2 rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-[#1e5a48] focus:border-transparent bg-white"
          >
            <option value="all">All statuses</option>
            <option value="active">Active</option>
            <option value="closed">Closed</option>
            <option value="defaulted">Defaulted</option>
            <option value="foreclosed">Foreclosed</option>
          </select>
        </div>
      </div>

      {/* Loans table */}
      <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm">
            <thead className="bg-gray-50 text-gray-600">
              <tr>
                <th className="p-4 font-medium">Loan</th>
                <th className="p-4 font-medium">Customer</th>
                <th className="p-4 font-medium">Vendor</th>
                <th className="p-4 font-medium text-right">EMI</th>
                <th className="p-4 font-medium text-right">Outstanding</th>
                <th className="p-4 font-medium">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {loading ? (
                <tr><td colSpan={6} className="p-8 text-center text-gray-500">Loading EMI loans...</td></tr>
              ) : filtered.length === 0 ? (
                <tr><td colSpan={6} className="p-8 text-center text-gray-500">
                  {loans.length === 0 ? 'No EMI loans yet. Click "New EMI Loan" to start.' : 'No loans match the current filters.'}
                </td></tr>
              ) : (
                filtered.map(l => (
                  <tr
                    key={l.id}
                    className="hover:bg-gray-50 cursor-pointer transition-colors"
                    onClick={() => navigate(`/admin/emi/loans/${l.id}`)}
                  >
                    <td className="p-4">
                      <p className="font-medium text-gray-800">{l.product_name}</p>
                      <p className="text-xs font-mono text-[#1e5a48]">{l.loan_code}</p>
                    </td>
                    <td className="p-4">
                      <p className="text-gray-800">{l.emi_customers?.full_name || '—'}</p>
                      <p className="text-xs font-mono text-gray-500">{l.emi_customers?.customer_code}</p>
                    </td>
                    <td className="p-4 text-gray-700">{l.vendors?.name || '—'}</td>
                    <td className="p-4 text-right font-medium">{formatCurrency(l.emi_amount)}</td>
                    <td className="p-4 text-right font-bold text-[#1e5a48]">{formatCurrency(l.remaining_principal)}</td>
                    <td className="p-4">
                      <StatusBadge status={l.status} />
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Create modal */}
      {isCreateOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4 backdrop-blur-sm">
          <div className="bg-white rounded-2xl shadow-xl w-full max-w-2xl overflow-hidden flex flex-col max-h-[92vh]">
            <div className="p-5 border-b flex justify-between items-center bg-[#0b3b2f] text-white shrink-0">
              <h3 className="font-bold text-lg">New EMI Loan</h3>
              <button onClick={() => setIsCreateOpen(false)} className="text-white/70 hover:text-white">
                <i className="fas fa-times text-xl"></i>
              </button>
            </div>
            <div className="p-6 overflow-y-auto">
              {formError && <div className="mb-4 p-3 bg-red-50 text-red-700 rounded-lg text-sm border border-red-100">{formError}</div>}

              <form onSubmit={handleCreate} className="space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label>Customer <span className="text-red-500">*</span></Label>
                    <select
                      className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                      value={customerId}
                      onChange={(e) => setCustomerId(e.target.value)}
                      required
                    >
                      <option value="">-- Select customer --</option>
                      {customers.map(c => (
                        <option key={c.id} value={c.id}>{c.customer_code} — {c.full_name}</option>
                      ))}
                    </select>
                  </div>
                  <div className="space-y-2">
                    <Label>Vendor <span className="text-red-500">*</span></Label>
                    <select
                      className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                      value={vendorId}
                      onChange={(e) => setVendorId(e.target.value)}
                      required
                    >
                      <option value="">-- Select vendor --</option>
                      {vendors.map(v => (
                        <option key={v.id} value={v.id}>{v.name}</option>
                      ))}
                    </select>
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label>Product Name <span className="text-red-500">*</span></Label>
                    <Input value={productName} onChange={(e) => setProductName(e.target.value)} required placeholder="e.g. Samsung Galaxy S24" />
                  </div>
                  <div className="space-y-2">
                    <Label>Product Category</Label>
                    <Input value={productCategory} onChange={(e) => setProductCategory(e.target.value)} placeholder="e.g. Mobile, Laptop, TV" />
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label>Product Price (₹) <span className="text-red-500">*</span></Label>
                    <Input type="number" value={productPrice} onChange={(e) => setProductPrice(e.target.value)} required min="1" step="1" placeholder="e.g. 50000" />
                  </div>
                  <div className="space-y-2">
                    <Label>Downpayment (₹)</Label>
                    <Input type="number" value={downpayment} onChange={(e) => setDownpayment(e.target.value)} min="0" step="1" placeholder="0 if no downpayment" />
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label>Interest Rate (% per annum, flat) <span className="text-red-500">*</span></Label>
                    <Input type="number" value={interestRate} onChange={(e) => setInterestRate(e.target.value)} required min="0" step="0.5" />
                  </div>
                  <div className="space-y-2">
                    <Label>Tenure <span className="text-red-500">*</span></Label>
                    <select
                      className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                      value={tenureMonths}
                      onChange={(e) => setTenureMonths(e.target.value)}
                      required
                    >
                      {TENURE_OPTIONS.map(t => <option key={t} value={t}>{t} months</option>)}
                    </select>
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label>Disbursed Date <span className="text-red-500">*</span></Label>
                    <Input type="date" value={disbursedDate} onChange={(e) => {
                      setDisbursedDate(e.target.value);
                      // Auto-shift first EMI date to one month later if user changes disbursed date
                      if (e.target.value) {
                        setFirstEmiDate(format(addMonths(new Date(e.target.value), 1), 'yyyy-MM-dd'));
                      }
                    }} required />
                    <p className="text-xs text-gray-500">Date we paid the vendor.</p>
                  </div>
                  <div className="space-y-2">
                    <Label>First EMI Due Date <span className="text-red-500">*</span></Label>
                    <Input type="date" value={firstEmiDate} onChange={(e) => setFirstEmiDate(e.target.value)} required />
                    <p className="text-xs text-gray-500">Typically 1 month after disbursement.</p>
                  </div>
                </div>

                <div className="space-y-2">
                  <Label>Vendor Invoice Number (optional)</Label>
                  <Input value={vendorInvoiceNumber} onChange={(e) => setVendorInvoiceNumber(e.target.value)} placeholder="From vendor's bill" />
                </div>

                <div className="space-y-2">
                  <Label>Notes (optional)</Label>
                  <textarea
                    value={notes}
                    onChange={(e) => setNotes(e.target.value)}
                    rows={2}
                    placeholder="Any internal notes about this loan"
                    className="flex w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring resize-none"
                  />
                </div>

                {/* Live EMI calc preview */}
                <div className="bg-[#1e5a48]/5 border border-[#1e5a48]/20 rounded-lg p-4">
                  <p className="text-sm font-bold text-[#1e5a48] mb-3 flex items-center gap-2">
                    <i className="fas fa-calculator"></i> EMI Preview
                  </p>
                  <div className="grid grid-cols-2 gap-3 text-sm">
                    <Stat label="Financed Amount" value={formatCurrency(calc.financed)} />
                    <Stat label="Total Interest" value={formatCurrency(calc.totalInterest)} />
                    <Stat label="Total Payable" value={formatCurrency(calc.totalPayable)} />
                    <Stat label="Monthly EMI" value={formatCurrency(calc.emi)} highlight />
                    <Stat label="Principal / EMI" value={formatCurrency(calc.principalPerEmi)} muted />
                    <Stat label="Interest / EMI" value={formatCurrency(calc.interestPerEmi)} muted />
                  </div>
                  <p className="text-xs text-gray-600 mt-3">
                    <i className="fas fa-info-circle"></i> Vendor will be paid {formatCurrency(calc.financed)} upfront on the disbursed date.
                  </p>
                </div>

                <div className="pt-2">
                  <Button type="submit" className="w-full" disabled={formLoading || calc.financed <= 0}>
                    {formLoading ? 'Creating…' : 'Create EMI Loan'}
                  </Button>
                </div>
              </form>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function StatusBadge({ status }: { status: string }) {
  const styles: Record<string, string> = {
    active:     'bg-green-100 text-green-700',
    closed:     'bg-gray-100 text-gray-700',
    defaulted:  'bg-red-100 text-red-700',
    foreclosed: 'bg-blue-100 text-blue-700',
  };
  return (
    <span className={`px-2.5 py-1 rounded-full text-xs font-bold capitalize ${styles[status] || 'bg-gray-100 text-gray-700'}`}>
      {status}
    </span>
  );
}

function Stat({ label, value, highlight, muted }: { label: string; value: string; highlight?: boolean; muted?: boolean }) {
  return (
    <div>
      <p className="text-xs text-gray-500">{label}</p>
      <p className={`font-bold ${highlight ? 'text-[#1e5a48] text-lg' : muted ? 'text-gray-600' : 'text-gray-800'}`}>
        {value}
      </p>
    </div>
  );
}

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}
